######### CONFIG #########
# Please do only edit this file if you know what you are doing
# Everything is configurable with an in-game command

# Saves the amounts of items that can be sold at once
itemQuantities:
  minAmount: 1
  maxAmount: 10

# Saves the minimum and maximum amount items can be sold for
itemPrice:
  minAmount: 50
  maxAmount: 5000